version: '3.5'
services:
  coredns:
    image: coredns/coredns:latest
    container_name: coredns
    restart: unless-stopped
    command: "-conf /etc/coredns/Corefile"
    ports:
      - "53:8080"
      - "53:53/udp"
    volumes:
      - ./config:/etc/coredns